---
title: Een Scratch-sprite toevoegen vanuit de bibliotheek
hero_image: images / banner.png
description: Een Scratch-sprite toevoegen vanuit de bibliotheek
original url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Voeg een sprite toe
