title: Adding a sprite from the Scratch library
hero_image: images/banner.png
subtitle: ...
description: Adding a sprite from the Scratch library
published: false
steps:
  - title: Step one
    duration: 60
