title: add-sprite-from-library
hero_image: images/banner.png
subtitle: add-sprite-from-library subtitle
description: add-sprite-from-library description
published: false
steps:
  - title: Step one
    duration: 60
