---
title: लाइब्रेरी से स्क्रैच स्प्राइट जोड़ना
hero_image: images/banner.png
description: लाइब्रेरी से स्क्रैच स्प्राइट जोड़ना
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: स्प्राइट जोड़े
