---
title: लाइब्रेरी से Scratch स्प्राइट शामिल करना
hero_image: छवियों / banner.png
description: लाइब्रेरी से Scratch स्प्राइट शामिल करना
original url:
theme: cc-प्रोटोटाइप
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "“scratch\""
steps:
  - 
    title: स्प्राइट शामिल करें
