---
title: Legge til et skrapsprite fra biblioteket
hero_image: images / banner.png
description: Legge til et skrapsprite fra biblioteket
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "ripe"
steps:
  - 
    title: Legg til en sprite
