---
title: Ein Scratch-Sprite aus der Bibliothek hinzufügen
hero_image: Bilder / Banner.png
description: Ein Scratch-Sprite aus der Bibliothek hinzufügen
original url: ""
theme: cc-Prototyp
duration: 1
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "kratzen"
steps:
  - 
    title: Fügen Sie ein Sprite hinzu
