---
title: Thêm một Sprite Scratch từ Thư viện
hero_image: images / banner.png
description: Thêm một Sprite Scratch từ Thư viện
original url:
theme: nguyên mẫu cc
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "vết trầy"
steps:
  - 
    title: Thêm một sprite
