---
title: Tilføjelse af et scratch-sprite fra biblioteket
hero_image: images/banner.png
description: Tilføjelse af et scratch-sprite fra biblioteket
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Tilføj en sprite
