---
title: Adding a Scratch sprite from the Library
hero_image: images / banner.png
description: Adding a Scratch sprite from the Library
original url:
theme: protótipo cc
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "coçar, arranhão"
steps:
  - 
    title: Add a sprite
