---
title: Adicionando uma animação (sprite) do Scratch a partir da Biblioteca
hero_image: images / banner.png
description: Adicionando uma animação (sprite) do Scratch a partir da Biblioteca
original url: ""
theme: protótipo cc
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Adicione uma animação sprite
