---
title: Добавяне на Scratch sprite от библиотеката
hero_image: изображения / banner.png
description: Добавяне на Scratch sprite от библиотеката
original url:
theme: сс-прототип
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "драскотина"
steps:
  - 
    title: Добавете спрайт
