---
title: Dodavanje ogrebotina od knjižnice
hero_image: slike / banner.png
description: Dodavanje ogrebotina od knjižnice
original url: ""
theme: cc-prototip
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "ogrepsti"
steps:
  - 
    title: Dodajte sprite
