---
title: Dodavanje Scratch lika iz knjižnice
hero_image: slike / banner.png
description: Dodavanje Scratch lika iz knjižnice
original url: ""
theme: cc-prototip
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "Scratch"
steps:
  - 
    title: Dodajte lika
