---
title: Dodavanje Scratch lika iz knjižnice
hero_image: images/banner.png
description: Dodavanje Scratch lika iz knjižnice
original url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "Scratch"
steps:
  - 
    title: Dodaj lika
