---
title: Adding a Scratch sprite from the Library
hero_image: Kuvien / banner.png
description: Adding a Scratch sprite from the Library
original url:
theme: CC-prototyyppi
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "naarmu"
steps:
  - 
    title: Add a sprite
