---
title: Scratch sprite -ohjelman lisääminen kirjastosta
hero_image: Kuvien / banner.png
description: Scratch sprite -ohjelman lisääminen kirjastosta
original url:
theme: CC-prototyyppi
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "naarmu"
steps:
  - 
    title: Lisää sprite
