---
title: Agregar un sprite de Scratch de la biblioteca
hero_image: images / banner.png
description: Agregar un sprite de Scratch de la biblioteca
original url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "rasguño"
steps:
  - 
    title: Añadir un sprite
