---
title: Ychwanegu ciplun Sgratch o'r Llyfrgell
hero_image: images/banner.png
description: Ychwanegu ciplun Sgratch o'r Llyfrgell
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Ychwanegu ciplun
