---
title: Ychwanegu corlun Sgratch o'r Llyfrgell
hero_image: images/banner.png
description: Ychwanegu corlun Sgratch o'r Llyfrgell
original url:
theme: cc-prototeip
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "crafu"
steps:
  - 
    title: Ychwanegu sbrithyn
