---
title: Eine Scratch-Figur aus der Bibliothek hinzufügen
hero_image: images/banner.png
description: Eine Scratch-Figur aus der Bibliothek hinzufügen
original url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Fügen Sie eine Figur hinzu
