---
title: Adăugarea unui personaj Scratch din Bibliotecă
hero_image: images/banner.png
description: Adăugarea unui personaj Scratch din Bibliotecă
original url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Adăugați un personaj
