---
title: Adăugarea unui sprite Scratch din Bibliotecă
hero_image: images / banner.png
description: Adăugarea unui sprite Scratch din Bibliotecă
original url: ""
theme: cc-prototip
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "zgârietură"
steps:
  - 
    title: Adăugați un sprite
