---
title: Adăugarea unui sprite Scratch din Bibliotecă
hero_image: imagini/banner.png
description: Adăugarea unui sprite Scratch din Bibliotecă
original url: ""
theme: prototip-cc
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Adăugați un sprite
