---
title: Adicionando um sprite Scratch da Biblioteca
hero_image: images/banner.png
description: Adicionando um sprite Scratch da Biblioteca
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Adicione uma sprite
