---
title: Menambahkan Scratch sprite dari Library
hero_image: gambar / banner.png
description: Menambahkan Scratch sprite dari Library
original url: ""
theme: cc-prototipe
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "menggaruk"
steps:
  - 
    title: Tambahkan sprite
