---
title: Menambahkan sprite Scratch dari Pustaka
hero_image: images/banner.png
description: Menambahkan sprite Scratch dari Pustaka
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Tambahkan sprite
