---
title: Dodajanje Scratch-jevega pisma iz knjižnice
hero_image: images / banner.png
description: Dodajanje Scratch-jevega pisma iz knjižnice
original url: ""
theme: cc-prototip
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "praska"
steps:
  - 
    title: Dodaj sprite
