---
title: A Scratch sprite hozzáadása a könyvtárból
hero_image: images / banner.png
description: A Scratch sprite hozzáadása a könyvtárból
original url:
theme: cc-prototípus
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "karcolás"
steps:
  - 
    title: Adj hozzá egy sprite-et
