---
title: Scratch szereplő hozzáadása a könyvtárból
hero_image: images/banner.png
description: Scratch szereplő hozzáadása a könyvtárból
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Adj hozzá egy szereplőt
