---
title: Ajout d'une image-objet Scratch à la bibliothèque
hero_image: images / banner.png
description: Ajout d'une image-objet Scratch à la bibliothèque
original url: ""
theme: cc-prototype
duration: 1
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "rayure"
steps:
  - 
    title: Ajouter un sprite
