---
title: 'title: إضافة كائن Scratch من المكتبة'
hero_image: 'hero_image: images/banner.png'
description: إضافة رمز سكراتش من المكتبة
original url:
theme: CC-النموذج
duration: 0
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "سكراتش"
steps:
  - 
    title: إضافة رمز
