---
title: 'title: إضافة كائن Scratch من المكتبة'
hero_image: 'hero_image: images/banner.png'
description: "description: إضافة كائن Scratch من المكتبة\n\noriginal url:"
original url:
theme: 'theme: cc-prototype'
duration: 0
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "technologies: \"scratch\""
steps:
  - 
    title: "steps:\ntitle: إضافة كائن"
