---
title: Dodawanie duszka Scratcha z biblioteki
hero_image: images/banner.png
description: Dodawanie duszka Scratcha z biblioteki
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Dodaj duszka
