---
title: Dodanie sprite'a Scratch z biblioteki
hero_image: images / banner.png
description: Dodanie sprite'a Scratch z biblioteki
original url: ""
theme: prototyp cc
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "zadraśnięcie"
steps:
  - 
    title: Dodaj duszka
