---
title: Dodanie duszka Scratcha z biblioteki
hero_image: images/banner.png
description: Dodanie duszka Scratcha z biblioteki
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Dodaj duszka
