---
title: Pridanie scratch sprite z knižnice
hero_image: images / banner.png
description: Pridanie scratch sprite z knižnice
original url:
theme: cc-prototyp
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "škrabanec"
steps:
  - 
    title: Pridajte sprite
