---
title: Lägga till en skrapsprite från biblioteket
hero_image: images / banner.png
description: Lägga till en skrapsprite från biblioteket
original url:
theme: cc-prototyp
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "repa"
steps:
  - 
    title: Lägg till en sprite
