---
title: Menambah sprit Scratch dari Perpustakaan
hero_image: imej / banner.png
description: Menambah sprit Scratch dari Perpustakaan
original url:
theme: prototaip cc
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "awal"
steps:
  - 
    title: Tambah sprite
