---
title: লাইব্রেরী থেকে একটি স্ক্র্যাচ স্প্রেড যোগ করা
hero_image: ইমেজ / banner.png
description: লাইব্রেরী থেকে একটি স্ক্র্যাচ স্প্রেড যোগ করা
original url: ""
theme: CC-প্রোটোটাইপ
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "আঁচড়ের দাগ"
steps:
  - 
    title: একটি পরী যোগ করুন
