---
title: Προσθέτοντας ένα Sprite Scratch από τη Βιβλιοθήκη
hero_image: εικόνες / banner.png
description: Προσθέτοντας μία μορφή (sprite) από τη Βιβλιοθήκη του Scratch
original url: ""
theme: cc-πρωτότυπο
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Προσθέστε μια μορφή (sprite)
