---
title: Dodavanje Scratch lika iz Biblioteke
hero_image: images/banner.png
description: Dodavanje Scratch lika iz Biblioteke
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Dodaj lik
