---
title: Ajout d'un lutin Scratch à la bibliothèque
hero_image: images / banner.png
description: Ajout d'un lutin Scratch à la bibliothèque
original url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Ajouter un lutin
