---
title: Aggiungere uno sprite di Scratch dalla Libreria
hero_image: images/banner.png
description: Aggiungere uno sprite di Scratch dalla Libreria
original url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Aggiungi uno sprite
