---
title: Aggiunta di uno sprite di Scratch dalla libreria
hero_image: images / banner.png
description: Aggiunta di uno sprite di Scratch dalla libreria
original url: ""
theme: cc-prototipo
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "graffiare"
steps:
  - 
    title: Aggiungi uno sprite
