---
title: Kütüphaneden bir Scratch sprite ekleme
hero_image: images / banner.png
description: Kütüphaneden bir Scratch sprite ekleme
original url:
theme: cc-prototip
duration: 1
curriculum:
listed: false
copyedit: true
ingredient: true
interests:
technologies: "çizik"
steps:
  - 
    title: Bir sprite ekle
